openapi: 3.0.3
info:
  title: Vaccine Docs API
  description: Vaccine Docs API - Alterra Academy
  version: 1.0.0
servers:
  - url: 'https://localhost:8080'

tags:
  - name: Healts Facilitators
    description: Sebuah lembaga yang bertanggung jawab melakukan vaksinisasi.
  - name: Citizens
    description: Masyarakat yang berhubungan dengan sistem

paths:
  /citizen/registers:
    post:
      tags:
        - Citizens
      description: citizens register to system
      summary: citizens register
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: juna@yawanmail.comn
                password:
                  type: string
                  example: wakwow123
                confirmation_password:
                  type: string
                  example: wakwow123
                full_name:
                  type: string
                  example: junaawjside
                NIK:
                  type: string
                  example: 123asdsad
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  meta:
                    $ref: "#/components/schemas/successResponse"
                  data:
                    $ref: "#/components/schemas/userRegisterResponse"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response404"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response500"


components:
  schemas:
    userRegisterResponse:
      type: object
      properties:
        email:
          type: string
          example: juna@yawanmail.comn
        full_name:
          type: string
          example: chefjuna
        NIK:
          type: string
          example: testing
    successResponse:
      type: object
      properties:
          status:
            type: integer
            example: 200
          message:
            type: string
            example: Success
    response404:
      type: object
      properties:
        meta:
          type: object
          properties:
            status:
              type: integer
              example: 400
            messages:
              type: string
              example: Error message put here...
    response500:
      type: object
      properties:
        meta:
          type: object
          properties:
            status:
              type: integer
              example: 500
            message:
              type: string
              example: Internal Server Error





  
